/*
 * SPDX-FileCopyrightText: 2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mesh_lite.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mesh_lite.pb-c.h"
void   mesh_lite__node_data__init
(MeshLite__NodeData         *message)
{
    static const MeshLite__NodeData init_value = MESH_LITE__NODE_DATA__INIT;
    *message = init_value;
}
size_t mesh_lite__node_data__get_packed_size
(const MeshLite__NodeData *message)
{
    assert(message->base.descriptor == &mesh_lite__node_data__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage*)(message));
}
size_t mesh_lite__node_data__pack
(const MeshLite__NodeData *message,
 uint8_t       *out)
{
    assert(message->base.descriptor == &mesh_lite__node_data__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage*)message, out);
}
size_t mesh_lite__node_data__pack_to_buffer
(const MeshLite__NodeData *message,
 ProtobufCBuffer *buffer)
{
    assert(message->base.descriptor == &mesh_lite__node_data__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage*)message, buffer);
}
MeshLite__NodeData *
mesh_lite__node_data__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (MeshLite__NodeData *)
           protobuf_c_message_unpack(&mesh_lite__node_data__descriptor,
                                     allocator, len, data);
}
void   mesh_lite__node_data__free_unpacked
(MeshLite__NodeData *message,
 ProtobufCAllocator *allocator)
{
    if (!message) {
        return;
    }
    assert(message->base.descriptor == &mesh_lite__node_data__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage*)message, allocator);
}
void   mesh_lite__data__init
(MeshLite__Data         *message)
{
    static const MeshLite__Data init_value = MESH_LITE__DATA__INIT;
    *message = init_value;
}
size_t mesh_lite__data__get_packed_size
(const MeshLite__Data *message)
{
    assert(message->base.descriptor == &mesh_lite__data__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage*)(message));
}
size_t mesh_lite__data__pack
(const MeshLite__Data *message,
 uint8_t       *out)
{
    assert(message->base.descriptor == &mesh_lite__data__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage*)message, out);
}
size_t mesh_lite__data__pack_to_buffer
(const MeshLite__Data *message,
 ProtobufCBuffer *buffer)
{
    assert(message->base.descriptor == &mesh_lite__data__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage*)message, buffer);
}
MeshLite__Data *
mesh_lite__data__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data)
{
    return (MeshLite__Data *)
           protobuf_c_message_unpack(&mesh_lite__data__descriptor,
                                     allocator, len, data);
}
void   mesh_lite__data__free_unpacked
(MeshLite__Data *message,
 ProtobufCAllocator *allocator)
{
    if (!message) {
        return;
    }
    assert(message->base.descriptor == &mesh_lite__data__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mesh_lite__node_data__field_descriptors[3] = {
    {
        "node_level",
        1,
        PROTOBUF_C_LABEL_NONE,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(MeshLite__NodeData, node_level),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "node_ip",
        2,
        PROTOBUF_C_LABEL_NONE,
        PROTOBUF_C_TYPE_UINT32,
        0,   /* quantifier_offset */
        offsetof(MeshLite__NodeData, node_ip),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "node_mac",
        3,
        PROTOBUF_C_LABEL_NONE,
        PROTOBUF_C_TYPE_BYTES,
        0,   /* quantifier_offset */
        offsetof(MeshLite__NodeData, node_mac),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};
static const unsigned mesh_lite__node_data__field_indices_by_name[] = {
    1,   /* field[1] = node_ip */
    0,   /* field[0] = node_level */
    2,   /* field[2] = node_mac */
};
static const ProtobufCIntRange mesh_lite__node_data__number_ranges[1 + 1] = {
    { 1, 0 },
    { 0, 3 }
};
const ProtobufCMessageDescriptor mesh_lite__node_data__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "mesh_lite.node_data",
    "NodeData",
    "MeshLite__NodeData",
    "mesh_lite",
    sizeof(MeshLite__NodeData),
    3,
    mesh_lite__node_data__field_descriptors,
    mesh_lite__node_data__field_indices_by_name,
    1,  mesh_lite__node_data__number_ranges,
    (ProtobufCMessageInit) mesh_lite__node_data__init,
    NULL, NULL, NULL  /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesh_lite__data__field_descriptors[1] = {
    {
        "nodes",
        1,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(MeshLite__Data, n_nodes),
        offsetof(MeshLite__Data, nodes),
        &mesh_lite__node_data__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};
static const unsigned mesh_lite__data__field_indices_by_name[] = {
    0,   /* field[0] = nodes */
};
static const ProtobufCIntRange mesh_lite__data__number_ranges[1 + 1] = {
    { 1, 0 },
    { 0, 1 }
};
const ProtobufCMessageDescriptor mesh_lite__data__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "mesh_lite.data",
    "Data",
    "MeshLite__Data",
    "mesh_lite",
    sizeof(MeshLite__Data),
    1,
    mesh_lite__data__field_descriptors,
    mesh_lite__data__field_indices_by_name,
    1,  mesh_lite__data__number_ranges,
    (ProtobufCMessageInit) mesh_lite__data__init,
    NULL, NULL, NULL  /* reserved[123] */
};
